[package]
name = "ponzu-back"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
dotenv = "0.15.0"
mongodm = "0.10.0"
serde = { version = "1.0.217", features = ["derive"] }
colored= "3.0.0"
